### ISSUE TITLE
Investigate single-threaded, async HTTP.request performance 

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#1032]
Stemming from [this discourse discussion](https://discourse.julialang.org/t/http-jl-async-is-slow-compared-to-python-aiohttp/96736/5)

**Comment by agoodm** [comment]
Thanks for mentioning this discussion here. After lots of digging I believe we have managed to narrow down MbedTLS being the culprit since running it with `socket_type_tls=OpenSSL.SSLStream` as well as the same URLs without HTTPS resulted in a dramatic speedup. 

I know that at this point other limitations arising from using MbedTLS have been discussed both here and [elsewhere](https://github.com/JuliaLang/julia/issues/48799), but maybe it would be a good idea to change the default to OpenSSL instead of MbedTLS?

**Comment by PallHaraldsson** [comment]
HTTP.jl already depends on MbedTLS.jl and OpenSSL.jl. I'm confused why. Liekly since you can choose either option, but since the latter is faster, should it default to it (as in the solution at the discourse thread) and MbedxLTS dependency be simply dropped? [That dependency is strictly not the same as MbedTLS in Julia itself, and the package should neither rely on that?]

[Going forward, some package like OpenSLL.jl would need auto-update mechanism, or even better provide nothing, just refer to the OS, that likely provides it for you?]

**Comment by quinnj** [comment]
Resolved in #1034 . Folks will still have to manually switch to OpenSSL for now, but I think we're getting close to switching that on by default.
