### ISSUE TITLE
Documentation links are all 404s

### ISSUE THREAD

**Issue by ararslan** [JuliaWeb/HTTP.jl#155]
https://juliaweb.github.io/HTTP.jl/stable and /latest

**Comment by samoconnor** [comment]
It looks like I have inadvertently pushed garbage to the gh-pages branch.
@quinnj do you know how to re-deploy the latests docs? I'm not familiar with the Documenter.jl gh-pages deployment scheme.

**Comment by samoconnor** [comment]
https://travis-ci.org/JuliaWeb/HTTP.jl/jobs/332068361#L6492

Maybe this will help: a22a44b2f5d9a91f898061659289f9ff7e252939

**Comment by ararslan** [comment]
Stable is still a 404, but that should be fixed with the next tag.

**Comment by mortenpi** [comment]
It should actually be easy to clean up the garbage on the `gh-pages` branch -- since it only has a single relevant commit, it shouldn't be a problem to just blow the branch up. You can delete the `gh-pages` branch on GitHub and then re-run the Travis build for `master` (just restart the build, no need to push anything to master). Documenter should create an empty `gh-pages` branch and re-deploy the `/latest` docs.

The `stable/` docs will deploy with the next tag, as @ararslan said.

**Comment by KristofferC** [comment]
Works now.
