### ISSUE TITLE
Startup is much slower than e.g. Requests.jl

### ISSUE THREAD

**Issue by staticfloat** [JuliaWeb/HTTP.jl#19]
I feel like we must be exercising a part of the compiler that doesn't normally get much exercise in this package, because startup times are particularly bad (this is on Julia 0.5):

```julia
julia> @time using Requests # (for reference)
  0.358254 seconds (329.11 k allocations: 15.328 MB)

julia> @time using HTTP
  4.433749 seconds (13.34 M allocations: 480.260 MB, 3.84% gc time)
```

Could this be another case where there's just a bunch of code in `Base` that isn't precompiled, and thus we need to mess around with `base/precompile.jl` in order to get this to speed up at all?

**Comment by quinnj** [comment]
Here's the rundown:

  * We have an almost 1000-line function in parser.jl that is a doozy to compile
  * Precompiling the function seems to not make that much of a difference
  * Instead of incurring that cost when the user makes the first request (which has the weird effect of messing w/ server response times and such), I'm currently including a dummy call to parse both a request and response in the module `__init__`. The idea being to move the compile time from call-time to module load time, which seems preferable IMO.
  * We could certainly run SnoopCompile again and that would probably help a bit, but yeah, I think there are issues w/ needing stuff in Base compiled.

Definitely open to ideas/suggestions here. I'll go ahead and ping @timholy, @jeffbezanson, and @vtjnash in case they have any comments to add.

**Comment by quinnj** [comment]
Ok, I'm committing a new round of SnoopCompile, but there are still issues. Basically we need to choose between faster module load time but slower first request vs. slower module load time but faster first request.

Faster module time, slower 1st request
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> @time using HTTP
  0.177277 seconds (219.88 k allocations: 10.711 MB, 5.39% gc time)

julia> @time HTTP.get("http://httpbin.org/ip")
  3.999866 seconds (4.58 M allocations: 179.157 MB, 1.18% gc time)
```

Slower module, but faster request
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> @time using HTTP
  6.079955 seconds (13.21 M allocations: 477.525 MB, 1.58% gc time)

julia> @time HTTP.get("http://httpbin.org/ip")
  1.659374 seconds (891.24 k allocations: 38.255 MB, 0.98% gc time)
```

From just looking at it, it seems we should go faster module load time, since the overall module-load + 1st-request is less than when we try to compile during init.

**Comment by quinnj** [comment]
Ref: 7a4a37c2dd2def58996825a609297a6a4daa5fe4

**Comment by quinnj** [comment]
Ok, I now get
```julia
julia> @time using Requests
  0.459076 seconds (328.42 k allocations: 15.348 MB)

julia> @time using HTTP
  0.159431 seconds (213.69 k allocations: 9.888 MB)
```
Which means we're 3x faster loading than Requests.
