### ISSUE TITLE
Basic Documentation

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [JuliaWeb/HTTP.jl#2]
Some very basic pieces of information should be found on the frontpage:

- Getting Started: How to start server, a typical Hello <username> Example, or something like that.
- The scope of this package. As I'm new to Julia's ecosystem, I would find it helpful to know which Web-components will be supported by this Package.
- Some notes on compatibility with other Packages, like WebSocket.jl, the SSL packages, etc,

**Comment by quinnj** [comment]
Alright, all docs are up [here](https://juliaweb.github.io/HTTP.jl/stable/). And to answer your more specific questions:

 * Scope of the package (currently): 
    * full client capabilities, including uri parsing/construction/validation/escaping, request/response parsing, client connection, persistent sessions, auto-cookie management, http/https, auto-redirect, auto-retry on io-fail requests, etc. 
    * basic server functionality: start a server to serve on a host and port, basic rate-limiting, auto-responses for server-level errors (500, request timeout, bad requests, etc.), abilities to put limits on read timeouts, max request uri size, max request headers size, max request body size, can toggle support for 100-Continue requests
    * In the future, I'm planning on splitting the URI code out and updating the existing URIParser package w/ the new code. I think it'd also make sense to split the client and server functionality. For now, I like keeping everything together so that it's that much easier to rapidly develop and iterate w/o having to mess with multiple packages. 

* compatibilities: currently websockets.jl aren't supported, but it's on my TODO list; part of the difficulty is how dated a lot of the webstack code is, it's been well worth my time to just start from scratch in a lot of places than try to use what was already out there. Currently MbedTLS.jl is the only true SSL package out there that I'm aware of (i.e. that's actively maintained), but I've also written both client & server functionality to use a sort of generic "TLS" interface so that in the future w/ different SSL implementations, it's a one-line change to use a separate SSL package than MbedTLS.
