### ISSUE TITLE
provide convenience helper function for constructing `file:///` URIs?

### ISSUE THREAD

**Issue by vtjnash** [JuliaWeb/HTTP.jl#241]
For example, see code and tests in PR to URIParser.jl: https://github.com/JuliaWeb/URIParser.jl/pull/60/files#diff-6c68f903474362a5d56664b6304e491bR59

**Comment by samoconnor** [comment]
Seems useful.

I wonder if it should be `URI(::Base.FilePath)`?
i.e. instead of putting the type in the method name (`URI_file`), add a type for strings that represent a local file path. This would be generally useful in many places.
(But I wouldn't want to force people to say `read(FilePath("myfile"))` where they can currently say `read("myfile")`).

**Comment by vtjnash** [comment]
What's Base.FilePath?
```
julia> Base.FilePath
ERROR: UndefVarError: FilePath not defined
```

**Comment by samoconnor** [comment]
> What's Base.FilePath?

>  ... add a type for strings that represent a local file path.

**Comment by quinnj** [comment]
ref: https://github.com/JuliaLang/Juleps/pull/26
