### ISSUE TITLE
Move AWS4 signing into a separate repo?

### ISSUE THREAD

**Issue by ararslan** [JuliaWeb/HTTP.jl#355]
Currently we have AWS Signature v4 signing in a single file with no tests (#291). In order to read the AWS credentials file, HTTP needs a dependency on IniFile. Neither IniFile nor AWS signing are used anywhere else in the repo. It would make sense to me to move this functionality out, allowing us to drop the dependency on IniFile. Folks who need to sign AWS requests can just do `using AWSSign` (or whatever).

**Comment by oxinabox** [comment]
In general isn't there a plan to move the whole of  the `AWS4AuthRequest` module out of the repo?

**Comment by oxinabox** [comment]
I feel like maybe @samoconnor  discussed it?
Part of the context where it came up was to do with priviledging AWS over say Azure or other providers with custom authish stuffs.

**Comment by samoconnor** [comment]
The AWS signing in HTTP.jl is copy/pasted from here : https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/sign.jl#L63

**Comment by samoconnor** [comment]
From https://github.com/JuliaWeb/HTTP.jl/pull/135#discussion_r161138979 ...



EricForgy on 12 Jan  Contributor
Why include AWS stuff in HTTP? 🤔
   @samoconnor
samoconnor on 12 Jan  Member

@EricForgy, 1) because it's needed support tests that use S3; 2) Because it served as an example of testing for myself how easy it would be for a user to add a custom layer to the stack; 3) because it seems like a natural peer of BasicAuthRequest.jl.
See also comments here about eventually splitting this all up into seperate packages: JuliaWeb/WebSockets.jl#84 (comment)
   @quinnj
quinnj on 12 Jan  Member
Yeah, this is not that much code for a pretty useful piece of functionality; it could easily move to AWSCore in the future, but for testing purposes, I'm totally ok w/ it living here.
   @samoconnor
samoconnor on 12 Jan  Member
The code is copy-pasted from AWSCore.jl.

Moving it back there at some point will serve as an interesting example of stack customisation because of how it interacts with other layers. e.g. The auth headers need to be recomputed after a redirect, and they need to know all the headers in the request, so the auth layer has to go at a particular layer in the stack. It will be nice to have an example of this for other users to follow.

**Comment by samoconnor** [comment]
Note: The performance tests still rely on S3 : https://github.com/JuliaWeb/HTTP.jl/blob/master/test/async.jl#L114

**Comment by oxinabox** [comment]
>  Note: The performance tests still rely on S3 : https://github.com/JuliaWeb/HTTP.jl/blob/master/test/async.jl#L114

can have a testime dependency for that

**Comment by ararslan** [comment]
Barring immediate, fervent objections I'm just going to go ahead with this then submit PRs to AWSCore and HTTP to take a dependency and test dependency, respectively, on the package. Thoughts on a name for the package?

**Comment by samoconnor** [comment]
AWSAuth.jl?

Does PKG3 have some way to keep multiple packages in one repo? (I recall some discussion about that) If so, perhaps AWSAuth.jl should be in the same repo as AWSCore.jl?

Do you intend to put `AWS4AuthRequest` in the new seperate package?
If so that would serve as a nice example of how to implement a custom HTTP layer in a seperate package.

> The auth headers need to be recomputed after a redirect, and they need to know all the headers in the request, so the auth layer has to go at a particular layer in the stack. It will be nice to have an example of this for other users to follow.

**Comment by ararslan** [comment]
> Does PKG3 have some way to keep multiple packages in one repo?

I believe that's planned functionality; I don't know of a way to do it currently.

> Do you intend to put AWS4AuthRequest in the new seperate package?

Yeah, that's the idea.

> If so that would serve as a nice example of how to implement a custom HTTP layer in a seperate package.

:+1: 

> AWSAuth.jl?

Not bad, though a bit general, as my thinking was to move just the AWS4AuthRequest functionality.

**Comment by samoconnor** [comment]
It would probably make sense to put [AWSCredentials.jl]( https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/AWSCredentials.jl) in the new module, it has more complete handling of `~/.aws/credentials`, env vars etc. The INI file stuff in `AWS4AuthRequest.jl` is a hack suitable for testing, but it only handles very simple configurations.

**Comment by samoconnor** [comment]
Note: this is where AWSCore.jl constructs it's HTTP stack: https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L31-L34

We'll need an api something like:
`insert!(stack::HTTP.Layer, insert_above::HTTP.Layer, new::HTTP.Layer)`

... so that  AWSCore.jl can do:
 `insert!(stack, HTTP.RetryLayer, AWSAuth.AWS4AuthRequest)`.

**Comment by ararslan** [comment]
I'm working on https://github.com/JuliaWeb/AWSAuth.jl. Still a work in progress so not much to see yet. It will need #358 in order to pass tests, at which point I'd like to do a bit of restructuring before adding more functionality.

**Comment by ararslan** [comment]
Just an update: AWSAuth is up and running with the basic functionality excised from HTTP, but isn't active or registered yet. I'll close this once the functionality is fully removed from HTTP.

**Comment by mattBrzezinski** [comment]
With this merge request going through: https://github.com/JuliaWeb/HTTP.jl/pull/443

We can now remove the `AWS4AuthLayer` and move it into a more appropriate package.

**Comment by nico202** [comment]
Any news on this? I'd like the inifile dependency to be removed

**Comment by quinnj** [comment]
Anyone willing to make a PR removing the AWS4AuthLayer and related machinery? Or at least marking it as deprecated and we can do a release to allow people to move?

**Comment by mattBrzezinski** [comment]
@quinnj  https://github.com/JuliaWeb/HTTP.jl/pull/486

**Comment by quinnj** [comment]
Resolved as a part of refactoring in #789
