### ISSUE TITLE
HTTP.get() returns no content though Requests.get() does

### ISSUE THREAD

**Issue by stephenbnicar** [JuliaWeb/HTTP.jl#36]
This may not be an issue, maybe it's just a usage question.  I'm not that experienced with HTTP requests, so apologies if I'm doing something obviously wrong here.

```julia
using HTTP

api_url = "https://www.bea.gov/api/data?"
api_key = "_my API key_"
api_method = "GetData"
api_dataset = "NIPA"

TableID = "5"
frequency = "Q"
years = "2014,2015"

querydict = Dict("UserID" => api_key,
                 "Method" => api_method,
                 "DatasetName" => api_dataset,
                 "TableID" => TableID,
                 "Frequency" => frequency,
                 "Year" => years,
                 "ResultFormat" => "JSON")

a = HTTP.get(api_url; query = querydict)
```
There appears to be no content returned:
```julia
HTTP.Response:
"""
HTTP/1.1 200 OK
Access-Control-Allow-Methods: GET, POST
Date: Sun, 05 Mar 2017 23:19:47 GMT
Age: 0
Access-Control-Allow-Origin: *
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Content-Length: 0
Access-Control-Max-Age: 60, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Type: text/html;charset=UTF-8
X-Frame-Options: SAMEORIGIN

"""
```

If I use `Requests.jl` for the identical query I get:
```julia
using Requests
b = Requests.get(api_url; query = querydict)
Requests.headers(b)

Dict{AbstractString,AbstractString} with 15 entries:
  "Access-Control-Allow-Methods" => "GET, POST"
  "Date"                         => "Sun, 05 Mar 2017 23:27:12 GMT"
  "Age"                          => "0"
  "Access-Control-Allow-Origin"  => "*"
  "http_minor"                   => "1"
  "Keep-Alive"                   => "1"
  "status_code"                  => "200"
  "Server"                       => "Microsoft-IIS/7.5"
  "X-Powered-By"                 => "ASP.NET"
  "Content-Length"               => "39247"
  "Access-Control-Max-Age"       => "60, must-revalidate"
  "http_major"                   => "1"
  "Strict-Transport-Security"    => "max-age=31536000; includeSubDomains"
  "Content-Type"                 => "application/json;charset=ISO-8859-1"
  "X-Frame-Options"              => "SAMEORIGIN"
```
This returns the data I anticipated which I can parse using `Requests.json()`.  (Incidentally, this request throws an error - `ERROR (unhandled task failure): HTTP Parser Exception: HPE_INVALID_CONSTANT(28):invalid constant string` -  though the data I'm looking for is still returned.)

I'd appreciate any help figuring out what's going wrong here.

**Comment by quinnj** [comment]
Ah, so this was an interesting one. So for whatever reason, the server in this case is sending back an extra space character `' '`at the end of the response body which isn't included in their `Content-Length` header byte size. This has the effect of throwing the http parsers off (for Requests & HTTP) because it only parses `Content-Length` # of bytes for the response body. Then, in the case of Requests, it continues parsing and you see the `unhandled task failure`, but it still returns the full Response body. In the case of HTTP.jl, we were throwing the error earlier because it was trying to parse an additional response after the end of the body. This is a "feature" left over from porting the http-parsing code from the C library where multiple response parsing logic was included at the parser level. For HTTP.jl, we do multiple response handling at the client level (i.e. client.jl), so this is never needed.

Thanks for the report! Even though the server is misbehaving here, we can certainly make our client code more robust to these kinds of cases.

If you pull latest master here (`Pkg.checkout("HTTP")`), you should be able to verify that the fix works for you.

**Comment by stephenbnicar** [comment]
Thanks a lot for the detailed response!  I knew the server was returning something "extra" but couldn't figure out exactly what it was and it's been driving me crazy.  

I checked out the master but, unfortunately, I'm still getting the same response from HTTP.get() - no error, but there's no content - the response is identical to the example I posted above.

**Comment by quinnj** [comment]
Ah yes, I forgot to mention that I needed to remove the "?" from your api_url. Glad it's working for you! Do let me know if you run into any other issues; the package is quickly getting a few kinks out and is shaping up to be a good webstack foundation for Julia.
