### ISSUE TITLE
How can I keep the websocket alive?

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [JuliaWeb/HTTP.jl#376]
After around one minute of successful exchange between a Julia websocket server and a browser client, I get a connection timeout. I guess the browser closes the connection (because Julia does not). So the question is: how can I ping the client so he keeps the connection alive?

I tried to write the WS_PING byte in the websocket, but it does not even send the message.

**Comment by zot** [comment]
I'm not positive on this but it appears that check_readtimeout, from the new release, is what is disconnecting the sockets upgrading to a websocket does not appear to cancel the timeout behavior. My code didn't timeout from the previous release but it does now.

**Comment by Hugo-Trentesaux** [comment]
Thanks, it will help me to debug it

**Comment by samoconnor** [comment]
@quinnj I haven't played with WebSockets ping-pong. However I think when #341 is fixed it shouldn't be needed.

**Comment by quinnj** [comment]
@samoconnor, I think we should either remove the websockets code or document that it shouldn't be used as it seems there are no real maintainers of the code. Thoughts?

**Comment by zot** [comment]
Wow, I'm sure using it!

**Comment by quinnj** [comment]
@zot, the main issue is the websockets code in HTTP.jl hasn't gotten nearly enough love since being added. If you're willing to step up and help maintain the code, we would gladly welcome the contributions. As is though, there are several outstanding websocket-related issues and no one working on them. It just makes me uncomfortable having that code in HTTP.jl and users expecting it to be at the same quality/standard as the rest of the package.

**Comment by zot** [comment]
WebSockets.jl seems to be actively maintained and it even imports a version of this package that is known to work with it. I suspect that the connection timeout behavior will still not play well with upgraded web socket connections though, since they reuse the socket and the timeout will close the connection.

I think there might need to be a way to protect an existing connection from timing out so that WebSockets.jl can use that to protect the connection from being closed from outside. Like maybe add a "notimeout" flag to Connection that check_readtimeout() can look at before closing the connection (maybe use it instead of wait_for_timeout?).

**Comment by samoconnor** [comment]
> @samoconnor, I think we should either remove the websockets code or document that it shouldn't be used as it seems there are no real maintainers of the code. Thoughts?

@quinnj are you aware of any current WebSockets issues that are non-#341 related ?
