### ISSUE TITLE
The Layers mechanism is not easily extensible

### ISSUE THREAD

**Issue by ararslan** [JuliaWeb/HTTP.jl#389]
## Context

I am currently working on excising the AWS Signature v4 signing functionality into a separate package, [AWSAuth](https://github.com/JuliaCloud/AWSAuth.jl) (see #355). Part of the functionality here is a `Layer` subtype for AWS Sig v4 authentication, `AWS4AuthLayer`, which gets added to the stack when calling `HTTP.request` with `aws_authorization=true`. I encountered the issue described below, which unfortunately prompted https://github.com/JuliaCloud/AWSAuth.jl/pull/10.

## The issue

A package can define a `Layer` subtype with a `request` method that does what you want, but there are some serious complications. One example is that not every `request(::Layer, args...)` method takes the same arguments, so to know how to formulate the next call to `request` in your method, you need to know where in the stack your layer is, so that you know the expected signature for the next call.

Internally, HTTP gets around this by having `HTTP.stack` define the layers in a specific order that works. In that case, the AWS authentication layer is not the outermost layer, and to ensure that the AWSAuth package puts the layer in the same spot, it would need to completely reconstruct the stack by hand, and ensure that any preprocessing that's done in the user-facing `request` methods that get called before those which take `Layer`s is taken care of. That essentially amounts to a reimplementation of `HTTP.request`.

## Resolution

I think a good goal here would be to provide something more easily extensible by packages, but I'm not sure exactly what that should look like. To make the current design really work for everyone, packages should be able to insert layers into the stack without too much trouble.

Thoughts? Ideas?

**Comment by non-Jedi** [comment]
For reference, below are all the existing `request` method signatures for current `Layer` types.

```julia
request(::Type{HTTP.RedirectRequest.RedirectLayer{Next}}, method::String, url::HTTP.URIs.URI, headers, body; redirect_limit, forwardheaders, kw...) where Next
request(::Type{HTTP.BasicAuthRequest.BasicAuthLayer{Next}}, method::String, url::HTTP.URIs.URI, headers, body; kw...) where Next
request(::Type{HTTP.AWS4AuthRequest.AWS4AuthLayer{Next}}, url::HTTP.URIs.URI, req, body; kw...) where Next
request(::Type{HTTP.CookieRequest.CookieLayer{Next}}, method::String, url::HTTP.URIs.URI, headers, body; cookies, cookiejar, kw...) where Next
request(::Type{HTTP.CanonicalizeRequest.CanonicalizeLayer{Next}}, method::String, url, headers, body; kw...) where Next
request(::Type{HTTP.TimeoutRequest.TimeoutLayer{Next}}, io::IO, req, body; readtimeout, kw...) where Next
request(::Type{HTTP.MessageRequest.MessageLayer{Next}}, method::String, url::HTTP.URIs.URI, headers::Array{Pair{SubString{String},SubString{String}},1}, body; http_version, target, parent, iofunction, kw...) where Next
request(::Type{HTTP.ExceptionRequest.ExceptionLayer{Next}}, a...; kw...) where Next
request(::Type{HTTP.RetryRequest.RetryLayer{Next}}, url, req, body; retries, retry_non_idempotent, kw...) where Next
request(::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{Next}}, url::HTTP.URIs.URI, req, body; proxy, socket_type, reuse_limit, kw...) where Next
request(::Type{HTTP.DebugRequest.DebugLayer{Next}}, io::IO, req, body; kw...) where Next
request(::Type{HTTP.StreamRequest.StreamLayer}, io::IO, request::HTTP.Messages.Request, body; response_stream, iofunction, verbose, kw...)
request(::Type{HTTP.ContentTypeDetection.ContentTypeDetectionLayer{Next}}, method::String, url::HTTP.URIs.URI, headers, body; kw...) where Next
```

There are only 3 main patterns there:

1. method, url, headers, body
   - `RedirectLayer`
   - `BasicAuthLayer`
   - `CookieLayer`
   - `CanonicalizeLayer`
   - `MessageLayer` (this method restricts type of headers; others do not)
   - `ContentTypeDetectionLayer`
2. url, request, body
   - `AWS4AuthLayer`
   - `RetryLayer`
   - `ConnectionPoolLayer`
3. io, request, body (3 times)
   - `TimeoutLayer`
   - `DebugLayer`
   - `StreamLayer` (this method restricts type of request; others do not)

Other than that, the `ExceptionLayer` accepts anything.

So basically, we have 3 "types" of layers where layers of type 1 must go before
the `MessageLayer` in the stack, layers of type 2 must go after the
`MessageLayer` and before the `ConnectionPoolLayer`, and layers of type 3 must
go after the `ConnectionPoolLayer` and before the `StreamLayer`. The only layers
other special ordering rule I see is that the `CanonicalizeLayer` should be the
last layer before `Message` layer.

We should be able to easily express allowable layer ordering in the type system,
defining the Following abstract types and aliases.

```julia
abstract type Layer end

# request methods that take pattern of input following list above
abstract type Input1Layer <: Layer end
abstract type Input2Layer <: Layer end
abstract type Input3Layer <: Layer end

abstract type PreMessageLayer{L <: Input1Layer} <: Input1Layer end
abstract type MessageLayer{L <: Input2Layer} <: Input1Layer end
abstract type PreConnectionLayer{L <: Input2Layer} <: Input2Layer end
abstract type ConnectionPoolLayer{L <: Input3Layer} <: Input2Layer end
abstract type PreStreamLayer{L <: Input3Layer} <: Input3Layer end
abstract type StreamLayer <: Input3Layer end
```

And then things like `RedirectLayer{L}` become a subtype of `PreMessageLayer{L}`,
`AWS4AuthLayer{L}` a subtype of `PreConnectionLayer{L}`, etc.

Other than the type hierarchy, the only change needed here would be to combine
the `CanonicalizeLayer` into `MessageLayer` or create something like an `Input1.5Layer` just
for it.

This should allow people to use the stack system by creating their own layers
and making their own stacks without having to worry that they're doing something
that won't work; the type system will prevent them doing such as long as they
follow the interfaces for `Input1Layer`, `Input2Layer`, and `Input3Layer`.

**Comment by iamed2** [comment]
Something helpful would be the ability to copy a stack and insert a layer into the proper place. I think a common case will be "do whatever the default is + MyLayer".

That does sound good though!

**Comment by non-Jedi** [comment]
@iamed2 Hm. To do that, you'd really need to be able to iterate through the
stack, which is going to be awkward if not impossible to program since the stack
of layers is an abstract type rather than a value. If we required all layers to
be represented by concrete values of types, it would be relatively simple I
suppose.

What if instead, we allowed passing a `Vector{UnionAll}` to the `stack` method
and then `stack` automatically inserted each `Layer` in the vector in the
correct part of the stack?

Otherwise, we may be looking at rearchitecting to use values to represent layers
instead of types.

**Comment by iamed2** [comment]
Could you not do traversal/insertion as you would with a linked list?

**Comment by non-Jedi** [comment]
Maybe you could, but I can't find a way. So for a `x = X{T}` datatype, you can use `getproperty(parentmodule(x), nameof(x))` to get the `UnionAll`, `X`. I have no idea how to get `T` in this scenario to continue traversing the stack.

**Comment by iamed2** [comment]
You'd want to put the `NextLayer` parameter into a common abstract supertype. 

Simplified example:
```julia
julia> abstract type Layer{Next} end

julia> next(::Type{<:Layer{T}}) where {T} = T
next (generic function with 1 method)

julia> abstract type MyLayer{Next <: Layer} <: Layer{Next} end

julia> next(MyLayer{MyLayer{Union{}}})
MyLayer{Union{}}

julia> next(ans)
Union{}
```

**Comment by non-Jedi** [comment]
Okay cool! So it's definitely possible and actually shouldn't even be too bad
taking advantage of multiple dispatch. So then to define an external layer with
all this, it would be as simple as:

```julia
abstract type MyLayer{L} <: PreMessageLayer{L} end

request(::MyLayer{L}, method, url, headers, body; kwargs...) where L =
    request(L, method url, headers, body; kwargs...)

mystack = insert(stack(), MyLayer)
```

That seems like a reasonable interface to me.

**Comment by christopher-dG** [comment]
I've found Elixir's [Plug](https://github.com/elixir-plug/plug) to be a really nice model for this kind of thing. Plugs are roughly equivalent to layers here, but all the data is passed around in a single `Conn` struct, instead of the large number of different signatures that we have, and plugs needn't be aware of what plugs come before or after them.

**Comment by non-Jedi** [comment]
At the very least, I think we can collapse method signatures 1 and 2 into a single method signature which should cover the majority of custom layer use-cases. That should simplify things and get us closer to the ideal of not caring about layer order whatsoever.

Just need to do all the things in method signature 1 layers as mutating functions on a `Request` object instead of passing distinct `method`, `url`, `headers`, and `body` arguments around. In fact even method signature 2 is kind of funky by passing `url` and `body` arguments despite those already existing wrapped in the `Request` object.

**Comment by samoconnor** [comment]
The `insert` function can be implemented like this... 

```julia
julia> abstract type Layer end

julia> abstract type FooLayer{Next <: Layer} <: Layer end

julia> abstract type BarLayer{Next <: Layer} <: Layer end

julia> abstract type LastLayer{Next <: Layer} <: Layer end

julia> stack = FooLayer{BarLayer{LastLayer}}
FooLayer{BarLayer{LastLayer}}

julia> abstract type NewLayer{Next <: Layer} <: Layer end

julia> function insert(stack::Type, after, new)
           layer = Base.typename(stack).wrapper
           next = stack.parameters[1]
           layer == after ? layer{new{next}} : layer{insert(next, after, new)}
       end
insert (generic function with 1 method)

julia> insert(stack, FooLayer, NewLayer)
FooLayer{NewLayer{BarLayer{LastLayer}}}

julia> insert(stack, BarLayer, NewLayer)
FooLayer{BarLayer{NewLayer{LastLayer}}}
```

Or, as @iamed2 suggests, if `Next` was made a parameter of `Layer`, then we could avoid using `parameters[1]`. However, the `parameters` field seems to be a fairly stable interface, so I'd be happy to use that.

**Comment by samoconnor** [comment]
> ... the ideal of not caring about layer order whatsoever

It seems to me that if someone has decided to implement a custom HTTP stack layer, it is precisely  because they need it to be executed in a certain order with respect to the existing layers. e.g. "I need to do thing X after the redirect layer, but before the retry layer". I don't think it is a helpful design goal to "make it as easy as possible to insert/replace any layer". The stack customisation API should make it clear that the ordering is important and that understanding of the [Internal-Architecture](https://juliaweb.github.io/HTTP.jl/stable/internal_architecture/#Internal-Architecture-1) is required. I think it makes sense to have documentation that says "if you just need to implement a custom authentication scheme, follow the AWSAuth example", but I think we should not create a false impression that modifying other layers is a simple matter.

The only use case where the user can get away with not caring about stack order is where they have a simple wrapper around `HTTP.request` (so the existing stack is unmodified).

>  I think we can collapse method signatures 1 and 2 into a single method signature.

I don't think it makes sense to try to collapse the method signatures. The different signatures reflect the different levels of abstraction that applies at each layer in the stack.

If you intend to insert a layer between A and B, you will be called by A and you will be responsible for calling B, you will have to fully understand the implicit interaction contract between A and B. The method signature is only part of this.

> 2 is kind of funky by passing url and body arguments despite those already existing wrapped in the Request object

The `body` argument is not the same as the `Request.body`.
See https://github.com/JuliaWeb/HTTP.jl/blob/master/src/MessageRequest.jl#L70-L77

**Comment by non-Jedi** [comment]
> The `body` argument is not the same as the `Request.body`.
> See https://github.com/JuliaWeb/HTTP.jl/blob/master/src/MessageRequest.jl#L70-L77

I'm still digesting the rest of your reply, but I thought I could at least respond to this bit. I realize that `Request.body` is not exactly the same as the `body` argument, but it is derived from the `body` argument. My plan here was to make `Request` parametric on the type of `body` and then just directly insert the `body` argument as `Request.body`. Then only call `bodybytes` on the `body` field when it's actually time to turn the entire `Request` object into bytes. This seems like a better design than duplicating that information.
