### ISSUE TITLE
Client cookie management has possibly poor ergonomics

### ISSUE THREAD

**Issue by non-Jedi** [JuliaWeb/HTTP.jl#398]
From a thread on reddit: https://www.reddit.com/r/Julia/comments/b0mi6y/is_julia_a_good_general_purpose_programming/eihqisq/

A user gave up on using HTTP.jl for making requests because they had difficulty getting it to do what they want with respect to managing cookies from client requests. Not sure what time period this is from, so things may have improved since then. Maybe this is just a documentation improvement? Full quote below:

>I did try, and iirc the documentation focuses on the server.
>
>Single Method actions were easy but managing sessions and updating client cookies got hairy quickly and the documentation didn't deal with that, I found myself trying to make sense of the source code but it is spread across too many modules to grok.
>
>It just wasn't worth the work to get what I had already.
>
>Maybe one day I will return to it, it shouldn't be so hard. I wrote one in shell script!
>
>https://plan9.io/sources/contrib/maht/rc/httplib.rc

**Comment by quinnj** [comment]
There's not much actionable here, but I apologize for the lack of follow up/response. Many updates have been made since this was originally posted, and this PR (https://github.com/JuliaWeb/HTTP.jl/pull/836) further improves some of the ergonomics. I'm planning a big documentation update soon that will also cover working with cookies.
