### ISSUE TITLE
eof hangs using websockets

### ISSUE THREAD

**Issue by lucianolorenti** [JuliaWeb/HTTP.jl#447]
Julia 1.2.0 
HTTP.jl 0.8.6
MbedTLS.jl 0.7.0

Hello. I am having an issue using the `eof` function of the WebSockets. 
Using the server provided in the Readme, and the following client:
```julia
julia> HTTP.WebSockets.open("ws://127.0.0.1:8081") do ws    
           @show eof(ws)
           write(ws, "Hello")           
           x = readavailable(ws)
           @show x
       end;
```
The client hangs. 
But if I put the `@show eof(ws)` under the `write(ws, "Hello")` line, the code does not hang.
```julia
julia> HTTP.WebSockets.open("ws://127.0.0.1:8081") do ws    
           write(ws, "Hello") 
          @show eof(ws)          
           x = readavailable(ws)
           @show x
       end;
```
The issue happens also if the eof is called after `readavailable(ws)`
What am I missing?

**Comment by zhanglix** [comment]
It is due to eof(::TCPSocket) will hang if there is no data available to read.

**Comment by quinnj** [comment]
@zhanglix is correct here and is one of the main reasons, in the newly merged overhaul of the websockets code on HTTP#master, I tried to move the `WebSocket` object and its API away from being IO-like. i.e. there's no `eof(ws)` method supported anymore because it's too easy to accidentally call this and it will just block forever waiting for a message to send. We now have a much more well-defined interface for how to work with a `WebSocket` object (check out the docs for `?WebSocket` on HTTP#master!) which should lead to a much more predictable/convenient usage.
