### ISSUE TITLE
TimeoutRequest refresh interval sleep time.

### ISSUE THREAD

**Issue by WNiels** [JuliaWeb/HTTP.jl#449]
HTTP.jl 0.8.6 

In [src/TimeoutRequest.jl](https://github.com/JuliaWeb/HTTP.jl/blob/master/src/TimeoutRequest.jl)

I have two questions about this line of code: 
`sleep(8 + rand() * 4)`

What is the benefit of waiting a randomized time until checking for a response?
Is it intentionally to pause for 8 to 12 seconds? Shouldn't it be milliseconds?

Thanks, Niels

**Comment by quinnj** [comment]
There's probably not a huge benefit to waiting a randomized time; but note that this is a timeout request: i.e. the default timeout is 60, so essentially `8 + rand() * 4` is just the amount of time we _would_ wait in between checks to see if we should _actually_ timeout. What would probably be a bit smarter would be to scale the sleep time in proportion to whatever the `readtimeout` is set at, because currently if you set a `readtimeout` at < 8 seconds, then it's not going to check for that timeout until `8 + rand() * 4` anyway. I'll make a PR.

**Comment by quinnj** [comment]
This has been fixed.
