### ISSUE TITLE
Early EOF with streaming

### ISSUE THREAD

**Issue by omus** [JuliaWeb/HTTP.jl#45]
In certain situations using `stream=true` will always return EOF:
```julia
julia> using HTTP

julia> stream = HTTP.body(HTTP.get("https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.1-linux-x86_64.tar.gz.asc", stream=true))
HTTP.FIFOBuffer(801,1048576,801,1,802,UInt8[0x2d,0x2d,0x2d,0x2d,0x2d,0x42,0x45,0x47,0x49,0x4e  …  0x54,0x55,0x52,0x45,0x2d,0x2d,0x2d,0x2d,0x2d,0x0a],Condition(Any[]),Task (done) @0x0000000114cd61d0,true)

julia> eof(stream)
true

julia> nb_available(stream)
801

julia> read(stream, 1)
1-element Array{UInt8,1}:
 0x2d

julia> eof(stream)
true
```

**Comment by quinnj** [comment]
Hmmm....I'm not sure I quite follow the issue here; as far as I can tell, the file being downloaded is indeed 801 bytes. In my experience, requests of this size are typically transferred wholly, which means when the first `readavailable(tcp)` is called, the entire response is received over the wire at once, parsed, and returned, thus rendering the `stream=true` somewhat moot since there was never a chance to return a partial response.

Are you expecting any different behavior here?

**Comment by omus** [comment]
The problem is that this doesn't follow the standard for `eof`. As the help for `eof` says:

> eof will return false as long as buffered data is still available, even if the remote end of a connection is closed.

Using the same example above:

```julia
julia> using HTTP;

julia> stream = HTTP.body(HTTP.get("https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.1-linux-x86_64.tar.gz.asc", stream=true));

julia> while !eof(stream)
           println(read(stream, UInt8))
       end

julia> length(read(stream))
801
```

**Comment by quinnj** [comment]
Ah, got it; yes, you're correct that we're ignoring if there are still bytes left in the buffer when doing the asynchronous `eof` check. Just pushed a fix.

**Comment by omus** [comment]
Thanks!

**Comment by omus** [comment]
@quinnj this issue isn't quite solved. If you end up reading from the FIFOBuffer before any data is written you can still get the early EOF:

```julia
using HTTP, Base.Test

i = 1
while i < 32
    stream = HTTP.body(HTTP.get("https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.1-linux-x86_64.tar.gz.asc", stream=true))
    while !eof(stream)
        read(stream, UInt8)
    end
    i += 1
end

@test i == 32
```

```julia
julia> @test i == 32
Test Failed
  Expression: i == 32
   Evaluated: 3 == 32
```

**Comment by quinnj** [comment]
Hmmm....unfortunately, I don't see a very easy fix for this. One idea I just had would be to always rely on the internal `.eof` field, even if not being used asynchronously. Upon construction, it'd be set to `false`, but then if all the bytes were read, it would set it to `true`, but only if not being used asynchronously. I'll play around w/ it a bit and see if it seems viable.

**Comment by quinnj** [comment]
Ok, just pushed a8ef427. Let me know if that solves it for you; it wasn't actually as involved a change as I thought it'd be.

**Comment by omus** [comment]
The problem still exists. Is there a reason we can't use the Content-Length header to determine the EOF?

**Comment by omus** [comment]
@quinnj can you re-open this issue?

**Comment by quinnj** [comment]
Hmmm....yeah, I'm wondering if we shouldn't set `f.eof` when reading. That would break mirroring IOBuffer, which I've been basing FIFOBuffer off of; I also kind of worry about the situation where you're not getting an `eof` so you keep reading and there are 0 bytes to read....I don't know, maybe it's ok.

**Comment by quinnj** [comment]
I've started looking deeper into this and I think it's actually an issue with `read(f::FIFOBuffer, ::Type{Tuple{UInt8, Bool}})` method because it's doing non-standard eof checking. Let me see if there's an easier fix there.

**Comment by quinnj** [comment]
Ok, just pushed a commit, this example works for me now
```julia
while i < 32
           stream = HTTP.body(HTTP.get("https://julialang.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.1-linux-x86_64.tar.gz.asc", stream=true))
           # sleep(1)  # Slowing down will allow data to be written to the buffer before we read
           while !eof(stream)
               read(stream, UInt8)
           end
           i += 1
       end
```

**Comment by omus** [comment]
Change looks to work ok. I want to play around with this a little more before I close the issue.

**Comment by quinnj** [comment]
Any other issues you've had @omus ?

**Comment by omus** [comment]
Sorry I haven't had time to make sure this is fixed. I'll try to verify this next week.

**Comment by omus** [comment]
Looking over af476cca6efa716c41f3e72d02d3264b0b6bb419 again I am still concerned that a fast enough `eof` call will give incorrect results:
```julia
julia> f = HTTP.FIFOBuffer(5)
HTTP.FIFOBuffer(0,5,0,1,1,UInt8[],Condition(Any[]),Task (runnable) @0x0000000118124fd0,0,-1)

julia> eof(f)
true

julia> write(f, 0x01)
1

julia> eof(f)
false
```

I think #49 is the way to go in order to avoid having an early EOF. The solution will only work reliably when the "Content-Length" is given but that should typically be provided.

**Comment by samoconnor** [comment]
@quinnj bump.
Any thoughts on the PR from @omus ?

I have a branch in AWSCore.jl to evaluate switching from Requests.jl to HTTP.jl : https://github.com/samoconnor/AWSCore.jl/commit/1e0744baa283a7c1bf4ce63b64c5983d943525eb

I haven't looked into the detail of this (#45) or the PR (#49), but it concerns me that maybe not all the corner cases are covered.

Is the spec any more complicated than this? : 

 - `eof()` is true if `Content-Length` bytes have been consumed by the reader.
 - `eof()` is true if the server has disconnected (cleanly or otherwise) and all buffered bytes have been consumed by the reader.
 - `eof()` is false in all other cases.

Some examples come to mind that should be covered by test cases: 

 - No Content-Length header and fragmented body. e.g. server returns some of the body, then gets hung up, e.g. waiting for a database read, before returning the rest of the body. Does the client hang around for the socket to be closed before returning eof()?

 - Content-Length is returned, but server does a clean socket close before returning the promised number of bytes. e.g. because some upstream resource failed. Does the FIFO reader get an immediate short read and eof()? or do they have to wait for a timeout?

 - The server disconnects before sending the header, or after sending only a partial header. e.g. some servers bail fast and hard on auth failure, or when throttling to shed load. In this case does the FIFO reader get an eof()? an exception? block forever?
