### ISSUE TITLE
HTTP.unescapeuri does not handle + sign

### ISSUE THREAD

**Issue by tk3369** [JuliaWeb/HTTP.jl#475]
Plus sign should be unescaped to space character.

```
julia> HTTP.unescapeuri("hello%20world")
"hello world"

julia> HTTP.unescapeuri("hello+world")
"hello+world"
```

For reference:
- https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1
- https://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20

Versions:
- Julia 1.2.0
- HTTP 0.8.8

**Comment by tk3369** [comment]
Another reference - Python3 urllib provides two functions to unquote uri's.  The `unquote_plus` function handles the plus sign.

https://docs.python.org/3/library/urllib.parse.html#urllib.parse.unquote_plus

**Comment by quinnj** [comment]
From what I can tell, `+` is only allowed in the query params portion of a URI; and various HTTP/URI libraries are all over the place on whether they allow this and how they handle the parsing of such. I don't think it's clear at all that `+` should automatically be parsed as a space from query params. I think I'd be ok having an `unquote_plus` function, but then again, the definition would simply be `unquote_plus(x) = replace(x, "+"=>" ")`, so I'm not sure it's really worth having since it's so easy.

**Comment by tk3369** [comment]
If I understand correctly from https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1, the `+` sign can appear in the body of a form POST as well when content type is `application/x-www-form-urlencoded`.

Having two separate functions would be fine.  Or, perhaps it could be a keyword arg for `HTTP.unescapeuri`?

While it's easy enough to handle this myself (which is what I'm doing currently), IMO it would be better when it's batteries included(TM).

**Comment by tanmaykm** [comment]
Got bitten by this now. Maybe a keyword argument to `unescapeuri` and a corresponding change to `escapeuri` to encode space as `+` would be good to have?

**Comment by quinnj** [comment]
Ok, here's a good automatic solution I came up with: https://github.com/JuliaWeb/HTTP.jl/pull/515. Essentially, `'+'` is only allowed to encode `' '` in query parameters, so the solution updates our `HTTP.queryparams(uri::URI)` function to decode them to spaces.
