### ISSUE TITLE
incorrect streamed output in case of redirect

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaWeb/HTTP.jl#526]
I'm using the `response_stream` argument to save an HTTP response directly to disk:
```jl
open(path, write=true) do io
    HTTP.get(url, response_stream=io, status_exception=false)
end
```
However, in this case if there is a redirect (301 or 302), then the body of the initial redirect response is what gets saved to the output file at `path` rather than what I want, which is the body of the final HTTP response in the redirect sequence.

HTTP v0.8.13
Julia Version 1.5.0-DEV.529
Commit 110e4356dc (2020-03-30 13:55 UTC)

**Comment by StefanKarpinski** [comment]
MWE, which I should have included yesterday:
```jl
julia> path = "Tar.jl-v1.1.0.tar.gz"
"Tar.jl-v1.1.0.tar.gz"

julia> url = "https://github.com/JuliaIO/Tar.jl/archive/v1.1.0.tar.gz"
"https://github.com/JuliaIO/Tar.jl/archive/v1.1.0.tar.gz"

julia> open(path, write=true) do io
           HTTP.get(url, response_stream=io, status_exception=false)
       end
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://render.githubusercontent.com
Content-Disposition: attachment; filename=Tar.jl-1.1.0.tar.gz
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/x-gzip
ETag: W/"c77b5e98c776086648d4e65ebb999b173ba3d87744ba8dfe0993aab5ea739149"
Strict-Transport-Security: max-age=31536000
Vary: Authorization,Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Date: Wed, 01 Apr 2020 14:12:38 GMT
X-Varnish: 169179390
Age: 0
Via: 1.1 varnish (Varnish/6.0)
X-Cache: MISS
X-Cache-Hits: 0
Accept-Ranges: bytes
Transfer-Encoding: chunked
X-GitHub-Request-Id: 99A7:78AF:3820:95EB:5E84A156

[Message Body was streamed]"""

shell> cat $path
<html><body>You are being <a href="https://codeload.github.com/JuliaIO/Tar.jl/tar.gz/v1.1.0">redirected</a>.</body></html>
```

**Comment by staticfloat** [comment]
So it appears that the issue is that the `StreamLayer` is invoked during the initial `request()` chain initiated by [the `RedirectLayer`](https://github.com/JuliaWeb/HTTP.jl/blob/6f262e64d3c0ef07d9bd8b9848afc07540b9bb22/src/RedirectRequest.jl#L24).  @samoconnor this is interesting, because I could see the use of having the `StreamLayer` be able to obtain the redirect itself, but in this case, it doesn't seem like that should be the default behavior.  What do you suggest?

**Comment by quinnj** [comment]
@staticfloat, having the StreamLayer isn't really the issue because it's actually a fundamental block in the stack; i.e. all requests go through the stream layer, regardless of whether the input/output are streamed or not. The issue, as far as I can tell from some debugging is that the `readbody` method closes the stream after writing the response to it, so that when the redirected response comes through the stream layer again, it's already closed, and then we have this curious behavior:
```julia
julia> io = open(path, write=true)
IOStream(<file Tar.jl-v1.1.0.tar.gz>)

julia> write(io, "hey there sailor")
16

julia> close(io)

julia> write(io, "hey tehre")
0
```
i.e. it's not an error to try to write to a closed IOStream, it just returns 0 bytes. This is in contrast to, say, IOBuffer which throws a "not writeable" error when you try to write to it after it's been closed.

I'm thinking through a few different solutions here (out loud, so forgive if they're ridiculous):
* we could _not_ close the `response_stream` in `readbody`, and maybe not even at all, since most people are calling like Stefan posted originally, in which the end of their do-block will close for them
* That would allow the 2nd response to at least be written, though it would be appended to the redirect, which seems undesirable; alternatives are we do a `seekstart` before writing each response, but then that could be weird if someone is expecting the response to be written to a very specific position in their response_stream.
* Another alternative is we try to save the current position of the response_stream in the RedirectLayer, then if we are redirecting, we'd seek back to that position before passing to the redirect; that would ensure we're at the right position. The one issue I can see there is if the response_stream isn't seekable, which is annoying, but I think a reality for some compressor IO types.
* Another option is we somehow detect in `readbody` that the response is a 301 _AND_ we haven't reached the redirect limit (which is usually only known/handled in the RedirectLayer) and just skip writing the response to the response_stream.
* Another alternative is we perhaps always buffer the response body in an IOBuffer and only "commit" it to the response_stream when we're sure we're at the end (were actually redirected or hit the redirect limit). This is kind of lame because of the extra buffering, which you're obviously trying to avoid when writing the response directly to the buffer.

I think I might play with the option of saving position and seeking in the RedirectLayer and then we can just document that the `response_stream` argument needs to be seekable.

**Comment by staticfloat** [comment]
Thanks for looking into this Jacob, I really appreciate it!

Some of the use cases that I'm using HTTP.jl for right now in the Pkg server are going to run afoul of some of these strategies.  As an example, to reduce latency when downloading large artifacts, it's really desirable for us to be able to start streaming files to processing tasks (such as decompression and content tree hashing) without having to wait to download the whole thing before it can start processing.  The tasks are also going to inspect the first couple of bytes to auto-determine the encoding of the response, so it is not really possible to support things like "write a bit, then rewind and write again".

It seems best to me to not write anything out to the `io` object unless it is associated with the actual resource that the user is interested in.  Otherwise, the number of `IO`-like objects that HTTP is compatible with will be restricted to those that support seeking and overwriting an internal buffer.

Without knowing anything about the internal architecture of HTTP.jl, my naive expectation would be that an HTTP 301 be handled differently than an HTTP 200: that its body is never written to the `io` object unless the option to follow redirects is false.

**Comment by quinnj** [comment]
Ok, alternative approach here: https://github.com/JuliaWeb/HTTP.jl/pull/552. I think it should work better because we take the approach of not writing to `response_stream` at all unless we know we won't follow any more redirects.
