### ISSUE TITLE
String(cookie, false) does not have domain info

### ISSUE THREAD

**Issue by felipenoris** [JuliaWeb/HTTP.jl#577]
Julia 1.5.0
HTTP.jl 0.8.17

From a server, given a `Response` I would like to append a cookie to it.

From the source code, I guess the best option I have is:

```julia
HTTP.appendheader(response, "Set-Cookie" => String(cookie, false) ) # isrequest = false
```

But that depends on `String` show all information about a Cookie.

But it looks like the domain does not gets into the string representation.

```julia
julia> cookie = HTTP.Cookie("my-cookie", "my-cookie-val", httponly=true, maxage=6*60*60, secure=true, domain="*.my-domain.net")
HTTP.Cookies.Cookie("my-cookie", "my-cookie-val", "", "*.my-domain.net", Dates.DateTime("0001-01-01T00:00:00"), 21600, true, true, false, String[])

julia> String(cookie, false)
"my-cookie=my-cookie-val; Max-Age=21600; HttpOnly; Secure"
```

**Comment by felipenoris** [comment]
[This](https://github.com/JuliaWeb/HTTP.jl/blob/f3a08d7fab731b907fc5ed5dfe0072eef5a2538f/test/messages.jl#L66) is also quite useful in this context. Maybe should be included in the package?

```
append_header(m, h) = appendheader(m, SubString(h[1]) => SubString(h[2]))
```

**Comment by quinnj** [comment]
Mind making a PR to add domain to the cookie `String` code? I'm also fine adding the `appendheader` method that takes a `Pair`; feel free to add that as well.

**Comment by felipenoris** [comment]
@quinnj sure!

**Comment by quinnj** [comment]
Ok, an update here. (sorry, I know this is like, years old)
  * In the original example, `domain="*.my-domain.net"` isn't actually a valid domain; it can start with a `.`, so `.my-domain.net` is valid, or `my-domain.net` is valid. But that's why it isn't printed in the cookie string operation.
  * In https://github.com/JuliaWeb/HTTP.jl/pull/836, I've added `HTTP.addcookie!(r, cookie)` where `r` can be a `HTTP.Request` or `HTTP.Response` and it will take care of the logic of adding the cookie to the request/response headers. I agree these are useful because there are just a few subtleties to be aware of.
