### ISSUE TITLE
Erratic behavior when working with spawned HTTP.request

### ISSUE THREAD

**Issue by NikEyX** [JuliaWeb/HTTP.jl#633]
Using:
* Julia 1.5.3
* HTTP v0.9.0
* MbedTLS.jl 1.0.3

I am getting really inconsistent results when doing http requests, especially when run in the same REPL. If you run the code below you would expect the 5 fast results (delay=0) to come in really quickly, followed by a result 10 seconds later for the spawned thread. 
```
using HTTP
using Dates

url_with_delay = "http://httpbin.org/delay/10"
url_fast = "http://httpbin.org/delay/0"

function httprequest(url)
    start = now()
    r = HTTP.get(url, connection_limit=500, pipeline_limit=500)
    return "$url, $(r.status), $start, $(now())"
end

t = Threads.@spawn httprequest($url_with_delay)
sleep(0.001)
@info httprequest(url_fast)
sleep(0.001)
@info httprequest(url_fast)
sleep(0.001)
@info httprequest(url_fast)
sleep(0.001)
@info httprequest(url_fast)
sleep(0.001)
@info httprequest(url_fast)
@info fetch(t)
```
For me this typically works the first time, but if you rerun the code, it will eventually get stuck at the first `httprequest(url_fast)` and wait for the spawned version to complete first. I've also seen it getting stuck on the third sometimes. Overall the behavior is very erratic.

Here is an example output, where you can see that all the end-times are at the same moment, indicating that each request was waiting for the 10 second request to complete:
```
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T18:57:32.745, 2020-11-30T18:57:32.769
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T18:57:32.773, 2020-11-30T18:57:32.797
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T18:57:32.803, 2020-11-30T18:57:32.823
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T18:57:32.829, 2020-11-30T18:57:42.765
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T18:57:42.771, 2020-11-30T18:57:42.796
[ Info: http://httpbin.org/delay/10, 200, 2020-11-30T18:57:32.739, 2020-11-30T18:57:42.762
```
but I also had one where the first fast-request was quickly completed and the last 4 fast-requests got stuck behind the thread:
```
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T19:04:40.091, 2020-11-30T19:04:40.331
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T19:04:40.337, 2020-11-30T19:04:50.164
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T19:04:50.17, 2020-11-30T19:04:50.208
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T19:04:50.214, 2020-11-30T19:04:50.251
[ Info: http://httpbin.org/delay/0, 200, 2020-11-30T19:04:50.256, 2020-11-30T19:04:50.28
[ Info: http://httpbin.org/delay/10, 200, 2020-11-30T19:04:40.078, 2020-11-30T19:04:50.156
```
FYI, I tested this with a local server as well and encountered the same problems, so it's not related to request throttling of httpbin.org or any of that I think.

Note that this is a problem that I encountered in a much larger project, so it's not just affecting the REPL.

**Comment by quinnj** [comment]
Ok, @NikEyX and I chatted on slack about this; it turns out that using the default `pipeline_limit` (which is 16) or setting `pipeline_limit=500` (as in the OP), is the key problem here. Pipelining in general is kind of a mixed-bag kind of optimization; if you happen to be sending a ton of requests with consistent response times, then it's a fine optimization, but in the case of requests with varying response times, it can actually be hurtful, as in OP. The problem is the slow request is written, then the connection is returned to the pool of available connections (because pipelining is allowed), then a fast request picks up the available connection and writes its request, but then has to wait for the previously written slow request response to come in before being able to read its own fast response. So setting `pipeline_limit=0` is an easy fix to ensure that each connection only handles a single request at a time through full write/read. It does mean the slow request "hogs" a connection for the length of its read/write, but in this case that's good because it means subsequent fast requests don't get stuck.

It makes me wonder if `pipeline_limit=0` should be the default, since most people probably don't realize pipelining is allowed by default and I'm really doubtful on how helpful it really is out in the wild. Any thoughts from anyeone?
