### ISSUE TITLE
Consistent exception types and error reporting

### ISSUE THREAD

**Issue by c42f** [JuliaWeb/HTTP.jl#792]
It would be good to have better consistency in error reporting and particularly exception types/codes. Currently HTTP.jl throws various sorts of exceptions and some can get thrown to the user from internal layers like Sockets (DNS lookup) and MBedTLS (unexpected stream errors).

This makes writing reliable applications on top of HTTP.jl quite hard, as you never know quite which error type to expect or what it means. In particular, which errors should be retried and which are likely permanent?  Related code:

* AWS.jl: https://github.com/JuliaCloud/AWS.jl/blob/179c6365009042868b6668163256a80c456f078b/src/utilities/request.jl#L176
* HTTPDownloads.jl: https://github.com/JuliaComputing/HTTPDownloads.jl/blob/a5fd409c91a3a669c2d8e0b5fc078ad49e63f46a/src/HTTPDownloads.jl#L174
* I think @tanmaykm had code somewhere which dealt with a big list of such possible errors but I can't find it now. Perhaps you could link or paste a snippet of the big list of exception types you'd encountered in production?

Overall I think HTTP.jl should probably wrap all errors it receives from internal layers into a minimal number of official HTTP.jl error types and document the circumstances in which they can be thrown. (For example, Downloads.jl has just one error type with many codes. I'm not sure what the best design is here.)

**Comment by tanmaykm** [comment]
Yes, I think the key is to have an easy way to distinguish between retryable (no request was sent) and non-retryable errors. So we had to look at the embedded error codes (e.g. `Libc.ECONNREFUSED` and dns lookup errors) and make a list of those that are retryable.

Maybe there are not too many of those, our list is big primarily because we are able to retry for some other error conditions as well, having knowledge of whether the API called was idempotent. But yes, having something in HTTP.jl to tell what can be retried safely in all cases and what can not will be a big plus.
