### ISSUE TITLE
Websocket not setting required mask?

### ISSUE THREAD

**Issue by tbenst** [JuliaWeb/HTTP.jl#794]
I'm running a trivial websocket server via node.js:

```javascript
import { WebSocketServer, WebSocket } from 'ws';

const wss = new WebSocketServer({ port: 1234 });

wss.on('connection', function connection(ws) {
  ws.send('something');
});
```

Here's the Julia client:
```julia
using HTTP

function test(ws_endpoint = "http://localhost:1234")
    HTTP.WebSockets.open(ws_endpoint) do ws
        while true
            if !eof(ws)
                msg = String(readavailable(ws))
                return msg
            end
        end
    end
end
test()
```
This results in an error (on js side) with code: WS_ERR_EXPECTED_MASK. It appears that `HTTP.WebSockets` is sending a message to server, and not using a mask. Hopefully I'm missing something, but right now I cannot receive a message from node.js in Julia.

cc https://github.com/JuliaWeb/HTTP.jl/issues/502

## versions
 - Julia 1.6.1
 - HTTP v0.9.17

**Comment by tbenst** [comment]
This appears to be a bug in HTTP.WebSockets, and it is not in spec.

The following works:
```
using WebSockets
function test(ws_endpoint = "http://localhost:1234")
    WebSockets.open("ws://127.0.0.1:1234") do ws_client
        data, success = readguarded(ws_client)
        if success
            println(stderr, ws_client, " received:", String(data))
        end
    end
end
test()
```

**Comment by quinnj** [comment]
Yes, the bug in the old websockets code is [here](https://github.com/JuliaWeb/HTTP.jl/blob/8c21c104b7b1e34c403655e180f6ae9dd1122ab3/src/WebSockets.jl#L182) where we were only writing the 1st two bytes of a frame directly to the underlying tcp socket. Only the old `wswrite` method took into account whether the websocket was client and needed to mask the message whens ending. In this case, there's actually no payload to send because it was intending to send a CLOSE frame with an empty body, but it failed to set the required `ismasked` bit of the frame flags and at least _include_ the mask, which is why the server was complaining, since servers are built to expect masking from clients or something is wrong.

The newly merged websockets code on HTTP#master fixes this.
