### ISSUE TITLE
readavailable returns 0 bytes

### ISSUE THREAD

**Issue by tbenst** [JuliaWeb/HTTP.jl#795]
I'm subscribing to topics on a webserver, and when I subscribe to 15 topics everything is fine, but when I subscribe to more, say 20 or 50, I start reading IO with 0 bytes. My code looks something like,

```julia
HTTP.WebSockets.open(ws_endpoint) do ws
  # [subscribe to topics by writing to ws]
  while true
    if !eof(ws)
      @info length(readavailable(ws))
    end
  end
end
```
And the output is something like,
```
[ Info: 88
[ Info: 88
[ Info: 88
[...]
[ Info: 88
[ Info: 88
[ Info: 0
[hangs]
```

I thought `!eof` should guarantee that at least 1 byte is read? I think what's happening is `HTTP.WebSockets.open` can't keep up with the message rate, as it's failing in 10-100K / s range, but succeeding around 1K / s (order of magnitude). However I'm not sure if this diagnosis is correct--I'm a bit at a loss for what could be going wrong.

I tried to create a MWE using a fast websocket server that ought to be able to create >10K messages / sec  but got stuck on https://github.com/JuliaWeb/HTTP.jl/issues/794

## versions
 - Julia 1.6.1
 - HTTP v0.9.17

**Comment by quinnj** [comment]
The problem in the old websockets code is that if an empty CLOSE message was received from the remote connection, this "empty message" was [returned to the user](https://github.com/JuliaWeb/HTTP.jl/blob/8c21c104b7b1e34c403655e180f6ae9dd1122ab3/src/WebSockets.jl#L308) instead of being thrown as an error which non-empty CLOSE messages would do.

I just merged an overhaul of the websockets code that fixes this, so HTTP#master should be correct now.
