### ISSUE TITLE
Difference in the format of path field of URI in HTTP.Request

### ISSUE THREAD

**Issue by sarvjeetsinghghotra** [JuliaWeb/HTTP.jl#83]
```julia
Routing.register!(r, ((req, res) -> HTTP.Response(201)), "/test", ["get"])
req = HTTP.Request()
req.uri = HTTP.URI(; path="/test", scheme="GET")
println("req1 ", HTTP.path(HTTP.uri(req)))

req1 = HTTP.Request()
req1.uri = HTTP.URI("/test")
println("req2 ", HTTP.path(HTTP.uri(req1)))
```
Output:
``` julia
req1 test
req2 /test
```

Shouldn't the path be `/test` in both the requests - `req` and `req1`.

**Comment by quinnj** [comment]
I think you may have messed something up when printing everything; I don't see any issues on current master
```julia
julia> b = HTTP.URI(; path="/test")
HTTP.URI("/test")

julia> a = HTTP.URI("/test")
HTTP.URI("/test")

julia> HTTP.path(a)
"/test"

julia> HTTP.path(b)
"/test"

julia>
```

**Comment by samoconnor** [comment]
I see the same result as @sarvjeetsinghghotra 
```
$ git log -1
commit ad5e5dfe35376e58f83a8c81fef2923688e94599 (HEAD, refs/remotes/origin/master, refs/heads/master)
Author: quinnj <quinn.jacobd@gmail.com>
Date:   Sat Aug 26 07:12:22 2017 -0600

    Require calling close on a FIFOBuffer to get eof. This removes the need for expectedlength/expectedpos and simplifies some of the processing logic without breaking any
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0
```
```julia
julia> using HTTP

julia> req = HTTP.Request()
HTTP.Request:
"""
GET / HTTP/1.1

"""

julia> req.uri = HTTP.URI(; path="/test", scheme="GET")
HTTP.URI("GET:test")

julia> println("req1 ", HTTP.path(HTTP.uri(req)))
req1 test

julia> req1 = HTTP.Request()
HTTP.Request:
"""
GET / HTTP/1.1

"""

julia> req1.uri = HTTP.URI("/test")
HTTP.URI("/test")

julia> println("req2 ", HTTP.path(HTTP.uri(req1)))
req2 /test

julia>
```

**Comment by quinnj** [comment]
Ok, I should clarify that doing scheme=GET doesn't make any sense. We should probably do validation on what's passed in as the scheme.

**Comment by samoconnor** [comment]
However, there are [valid use cases for custom schemes](https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uris-native-apps/#custom-scheme)

It's a little surprising that the leading `/` is preserved in the `http` example below but not the `foo` example...
```julia
julia> uri = HTTP.URI(; path="/xyz", scheme="foo")
HTTP.URI("foo:xyz")

julia> uri = HTTP.URI(; path="xyz", scheme="foo")
HTTP.URI("foo:xyz")

julia> uri = HTTP.URI(; path="xyz", scheme="http")
HTTP.URI("http://xyz")

julia> uri = HTTP.URI(; path="/xyz", scheme="http")
HTTP.URI("http:///xyz")
```

also, the displayed URI result itself does not parse:

```julia
julia> HTTP.URI("foo:xyz")
ERROR: HTTP.URLParsingError: encountered invalid host character:
foo:xyz
----^
```
"connect requests" ?
```julia
julia> HTTP.URI("mailto:foo@bar.com")
ERROR: HTTP.URLParsingError: connect requests must contain and can only contain both hostname and port
```

**Comment by quinnj** [comment]
We're mainly relying on the underlying http-parser library url parsing code here, which doesn't seem to support `mailto:` schemas. It probably wouldn't be too hard to enhance the underlying code to support it, but it would take someone willing to dive into some scarier looking code.

**Comment by samoconnor** [comment]
These examples seem to work on with URIParser.jl:
```julia
julia> URIParser.URI("mailto:foo@bar.com")
URI(mailto:foo@bar.com)

julia> URIParser.URI("foo:xyz")
URI(foo:xyz)
```

@quinnj, I'm confused when you say "relying on underlying http-parser library url parsing code", I though that HTTP.jl was self contained and has its own url parsing code. When you said that the URIParser has "gone through a complete re-write" I assumed that you meant re-written by you. Is that not the case? If not, who wrote the "scarier looking code"? and who understands it?

**Comment by quinnj** [comment]
URIParser.jl did their own (slow) port of the http-parser.c code to julia and it looks like they manually added support for `mailto` (https://github.com/JuliaWeb/URIParser.jl/blob/0ee051738dab941a467f1d49bead09b1d100a1c0/src/parser.jl#L218).

HTTP.jl is indeed self contained and has it's own url parsing code. Yes, rewritten by me. I understand it decently. Do I have an interest in doing the `mailto` change? Not really. If someone needs it direly then sure, I can do it. I was trying to make the point that it wouldn't be too bad for someone else to dive in and add support for it if they wanted.

**Comment by samoconnor** [comment]
I just noticed that there is a test case for "mailto" in HTTP.jl/test but the test calls `parse()` not `HTTP.URI()`.
Why does the example below work through `parse()` but not though `HTTP.URI()` (see above): ? 
```julia
julia> parse(HTTP.URI, "mailto:John.Doe@example.com")
HTTP.URI("mailto:John.Doe@example.com")
julia> parse(HTTP.URI, "foo:bar")
HTTP.URI("foo:bar")
```

It doesn't seem right for HTTP.jl to have functional regressions compared to URIParser.jl.
The advertising statements like "Performant, robust HTTP client and server functionality for Julia"
 and ["a concerted effort to revive, modernize, and improve"](https://discourse.julialang.org/t/ann-new-http-jl-package/2048) are going give users the impression that `HTTP.jl` is a step up from what came before.

You say that URIParser.jl is slow, but I can't [find any issue reports about performance problems](https://github.com/JuliaWeb/URIParser.jl/issues?utf8=✓&q=is%3Aissue). In my experience URIParser.jl never showed up as a performance bottleneck. Do you have a use-case where the HTTP.jl's superior URI parsing performance makes a significant difference?

**Comment by quinnj** [comment]
Performance benchmark: https://github.com/JuliaWeb/HTTP.jl/pull/9

I have a hard time reading your tone over the internet. On the one hand, you seem enthusiastic about the package and I appreciate all the feedback/issues; other other hand, some of your comments/feedback seem to come with a tone of "scathing disbelief" in some of the design decisions or issues you've run into. Perhaps I'm reading too much into things, but I thought I'd at least express that the tone makes me a little uncomfortable.

Do I think HTTP.jl is a step up from existing webstack packages? Leaps & bounds. I use it daily in production workflows and it performs extremely well and includes a number of features that simply don't exist in the older, un-maintained webstack packages. 

Are there going to be minor bugs here & there? Definitely. And I hope I've shown my willingness to fix them as quickly as possible. Looks like this is simply a minor bug in the difference between `HTTP.URI(str)` and `parse(HTTP.URI, str)`.

Is the performance difference significant? Yes. By at least 3x. Do you really not care about microbenchmarks? Like, I understand the whole "this probably won't be a performance concern on a macro scale all things considered", but I subscribe more to the philosophy of, "if you can make it fast, make it fast". It's not a performance problem until it is, right? Maybe you personally haven't run into those bottlenecks, but I can easily imagine a case where someone's trying to parse URLs on a memory-constrained device and need speed and HTTP.jl is going to leave URIParser.jl in the dust on both accounts.

Anyway, I do appreciate all the feedback; I'd also appreciate a more friendly tone on some of these issues.

**Comment by samoconnor** [comment]
Hi @quinnj,

I apologise if some of my criticism comes across as unfriendly. It can be difficult to convey intended tone over the internet. I am certainly enthusiastic about your enthusiasm for taking on the mammoth task that you have, and about the effort you've put in. I'm also enthusiastic about the improvements you've made.

I'm spending time using and testing the package for three reasons:

1. I want to support your efforts because I think it's essential for Julia to have a robust network stack. This stuff has to "just work" for Julia as a platform to be taken seriously. No one will notice in 5 years, "HTTP works really nicely on Julia", they will just expect it. But people will still complain if things don't work for their corner case. So, what you have taken on is a thankless task, with not much glory at the end. But it is a very important task. 

2. I have some experience with networks and protocols, so I hope this is an area where I can do more than just complain when things don't work, and where my time will add value to the outcomes. 

3. I'm building Julia systems that rely on HTTP, so I'm an end-user who needs to decide between staying with devil I know, or taking a leap to something new and promising but green. I'm a customer deciding between two vendors. I'm trying to answer questions like: Will HTTP.jl be functionally reliable? How long will the development momentum hold up? Is HTTP.jl well architected? How long will it take for HTTP.jl to reach critical mass and replace the older packages? Will I be able to understand the code and fix things myself if it comes to that? 

So far, I'm impressed by most of what I see, I have some lingering concerns, but you've been very responsive at addressing the function problems I've found.

You might not be surprised if I tell you that you are not the first person who has found my tone abrasive. I apologise again if I've said anything that's dampened your enthusiasm for working on this stuff. That is not my intention.

When it comes to performance, I am calibrated something like this: 1) Make the code correct; 2) Make the code easy to understand; 3) Mask sure the architecture does not preclude later optimisation of the components; 4) Make sure performance is reasonable for high-level real-world use cases. 5) Spend time on things that make a significant difference to real-world high-level benchmarks.
Everyone is calibrated differently. If your bent is micro-benchmarking, and making the little things faster because no one else bothers to to that, then thats great, everyone will benefit even if the time savings are only small. It seems to me that the two points of view are complimentary. If I feel the need to whack you with the make-it-correct-and-understandable stick, I'll try to whack more gently in future ;)

**Comment by quinnj** [comment]
Thanks for the response @samoconnor, it's great to hear your enthusiasm and willingness to alpha/beta test all this. I whole-heartedly agree that in 5 years, everyone is going to expect to have a solid webstack foundation to use for day-to-day tasks that "just work".

I just pushed a fix for some of the URI issues mentioned here. The main problem is I created my own `HTTP.URI` constructor as a convenience method for the client request functions to allow the user to pass in the url and query separately. I've now renamed that method to `HTTP.URL` and use that internally, while `HTTP.URI` matches what was exposed in URIParser.jl. Hopefully that clears up any confusion.
