### ISSUE TITLE
Try to escape userinfo portions of URLs before parsing

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/HTTP.jl#90]
Ref: https://discourse.julialang.org/t/authorize-rest-request-if-is-in-username/5869

**Comment by samoconnor** [comment]
This does not seem possible to me.
How can we escape the userinfo portion of a URL before parsing, if, in order to extract the userinfo portion, we must first parse the URL.

Perhaps we could add a line here: https://github.com/JuliaWeb/HTTP.jl/blob/master/src/URIs.jl#L90
to escape the `userinfo` when _constructing_ a new URL.
