### ISSUE TITLE
Some google weirdness

### ISSUE THREAD

**Issue by malmaud** [JuliaWeb/HTTP.jl#99]
```
julia> String(take!(HTTP.get("http://google.com")))
11983-byte String of invalid UTF-8 data:
 0x3c
 0x21
 0x64
...
```

yet

```
julia> String(take!(HTTP.get("http://nytimes.com")))
"<!DOCTYPE html>
...
```

**Comment by quinnj** [comment]
The issue here is that google is returning `Content-Type: text/html; charset=ISO-8859-1`, so it's not UTF8 anyway. We have an open issue about it #38. I tried digging around to see if there's way to ensure we always get utf8 back, but it seems like even passing `Accept-Charset` is not enough. I'll keep digging around.

**Comment by quinnj** [comment]
Going to close as a dup for now

**Comment by quinnj** [comment]
Note that this now works on current master; if we detect ISO-8859-1, it will convert to UTF8 when you do `String(::Response)`

**Comment by malmaud** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/ef534e16-69f9-4568-92e4-554ab1d99d40-d3c5ab13-c856-40df-958e-10c88c930386-v1.png?transparent=1&palette=1&width=246)
